export const MESSAGES_LIST_REQUEST = 'MESSAGES_LIST_REQUEST';
export const MESSAGES_LIST_SUCCESS = 'MESSAGES_LIST_SUCCESS';
export const MESSAGES_LIST_FAILED = 'MESSAGES_LIST_FAILED';

export const CHANGE_ACTIVE_FRIEND = 'CHANGE_ACTIVE_FRIEND';
